telegram_token: "alalaa"
accounts:
  - name: "acc name"
    username: "user"
    password: "pass"
allowed_chat_ids:
  - 1123456677
  - 1872918
known_vending_devices:
  - id: 123
    name: "Vending device 1"
